config/routes.rb
Itshare::Application.routes.draw do
  resources :users do
    resources :messages, only: [:index, :new, :create, :destroy]
  end

  resources :jobs do
    resources :job_comments, only: [:create]
  end

  resources :reviews do
    resources :review_comments, only: [:create]
  end

  resources :experiences do
    resources :comments, only: [:create]
  end

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  get 'index', to: 'index#index'
  get 'about', to:'about#index'

  get 'auth/github', to: 'openid#github_auth', as: :auth_github

  get 'auth/github/callback', to: 'openid#github_auth_succeed'

  root to: 'index#index'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :signed_in_user, except: [:index, :show]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.paginate(page: params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviews }
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])
    unless flash[:just_created_or_updated]
      @review.pageview += 1
      @review.save
    end
    @review_comment = ReviewComment.new

    @review_comments = @review.review_comments.paginate(page: params[:page])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  def new
    @review = Review.new
    @review.original = true
    @review.private = false
    @review.comment_able = true
  end

  def edit
    @review = Review.find_by_id_and_user_id(params[:id], current_user.id)
    if @review.nil? then
      redirect_to root_path
    end
  end

  def create
    @review = Review.new(params[:review])
    @review.user = current_user

    if @review.save
      flash[:just_created_or_updated] = true
      redirect_to @review
    else
      render action: "new"
    end
  end

  def update
    @review = Review.find(params[:id])

    if @review.update_attributes(params[:review])
      flash[:just_created_or_updated] = true
      redirect_to @review
    else
      render action: "edit"
    end
  end

  def destroy
    @review = Review.find_by_id_and_user_id(params[:id], current_user.id)
    if @review.nil? then
      redirect_to root_path
    end
    @review.destroy

    redirect_to reviews_url
  end

  def new_record_path(for_side_bar = false)
    for_side_bar ? new_review_path : (%w(index show).include?(action_name) ? new_review_path : nil)
  end
end

app/views/reviews/_form.html.erb
<%= form_for(@review, builder: CustomFormBuilder, :html => {class: 'table-bordered border-left margin-bottom20'}) do |f| %>
  <div class="top-title-container" style="padding: 0 10px; line-height: 40px;">
    <%= link_to 'Home', root_path %>
    <span class="divider">/</span>
    <%= link_to (t "controller.#{controller_name}"), reviews_path %>
    <span class="pull-right">
      <%= f.submit '立即发表', :class => 'btn btn-primary', style: "margin-top: -5px;" %>
      <%= link_to '取消', :back, :class => 'btn', style: "margin-top: -5px;" %>
    </span>
  </div>

  <div class="padding10">
    <h4><%= @review.new_record? ? '发表文章' : '编辑文章' %></h4>
    <hr/>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.text_field :title, required: true, label_class: 'v-form-label', field_tip: '最多24个字符' %>
    <%= f.text_field :company, label_class: 'v-from-label' %>
    <div class="field">
      <span style="float: left;height: 20px;">
        <%= f.label_for :details, required: true, label_class: 'v-form-label' %>
      </span>
      <div class="text-success" style="margin-left:60px;margin-bottom: 5px;">
        {回车产生&lt;p&gt;, Shift+Enter产生&lt;br/&gt;}
      </div>
      <%= f.kindeditor :details, width: '79%', height: '450px', items: f.default_kindeditor_items %>
    </div>
    <%= f.text_field :keywords, label: '好的关键字可以让别人更容易找到此篇文章', style:'width: 350px',
                     label_class: 'v-form-label margin-top25', field_tip: '多个关键字用半角逗号隔开，最多5个' %>
    <%= f.radio_buttons :original, [1, 0], label: "文章类型：", label_class: 'form-label text-bold', labels: ["原创", "转帖"] %>
    <%= f.radio_buttons :private, [0, 1], label: "隐私设置：", label_class: 'form-label text-bold',
                        labels: ["所有人可见", "保密（只有本人可见）"], field_tip: '设置为保密的文章，标题对任何人是可见的' %>
    <%= f.radio_buttons :comment_able, [1, 0], label: "评论设置：", label_class: 'form-label text-bold', labels: ["允许评论", "禁止评论"] %>
  </div>

  <div class="bottom-title-container" style="padding: 0 10px; line-height: 40px;">
    <%= link_to 'Home', root_path %>
    <span class="divider">/</span>
    <%= link_to (t "controller.#{controller_name}"), reviews_path %>
    <span class="pull-right">
      <%= f.submit '立即发表', :class => 'btn btn-primary', style: "margin-top: -5px;" %>
      <%= link_to '取消', :back, :class => 'btn', style: "margin-top: -5px;" %>
    </span>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<%= render 'form' %>

app/views/reviews/index.html.erb
<div class="table-bordered border-left">
  <div class="top-title-container text-article-info">
    共检索到 <%= @reviews.count %> 条记录
    <%= will_paginate %>
  </div>

  <% @reviews.each do |review| %>
    <div class="row-fluid border-bottom" style="padding-bottom: 10px;">
      <div class="padding10">
        <div class="pull-left">
          <%= link_to add_cdn_path(image_tag 'portrait.gif', class: 'thumbnail portrait'), user_path(review.user) %>
        </div>
        <div class="span10 article-list word-wrap" style="margin-left: 10px;">
          <%= link_to review.title, review_path(review), class: 'title' %>
          <br />
          <span class="text-article-info">
            <% unless review.company.strip.empty? then %>
              @<%= review.company %>
              <span class="dot-divider">•</span>
            <% end %>
            <%= review.user.name %>
            <span class="dot-divider">•</span>
            <% if review.review_comments.any? then %>
              最后由 <%= review.review_comments.last.user.name %> 于<%= review.review_comments.last.created_at_from_now %>回复
            <% else %>
              于<%= review.created_at_from_now %>发布
            <% end %>
            <% if review.review_comments.count > 0 then %>
              <span class="dot-divider">•</span>
              共<%= review.review_comments.count %>条回复
            <% end %>
          </span>
        </div>
        <% if signed_in? && current_user?(review.user) then %>
          <div class="pull-right">
            <%= link_to add_cdn_path(image_tag 'edit_16.png', alt: t('common.edit_btn_label'), title: t('common.edit_btn_label')), edit_review_path(review) %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

  <% if @reviews.any? then %>
    <div class="bottom-title-container text-article-info">
      共检索到 <%= @reviews.count %> 条记录
      <%= will_paginate %>
    </div>
  <% end %>
</div>

app/views/reviews/new.html.erb
<%= render 'form' %>

app/views/reviews/show.html.erb
<div class="table-bordered border-left margin-bottom20">
  <div class="top-title-container higher">
    <div class="pull-left">
      <h4 class="inline"><%= @review.title %></h4><br/>
      <span class="text-article-info">
        <%= link_to (t "controller.#{controller_name}"), reviews_path %>
        <span class="dot-divider">•</span>
        <%= @review.user.name %>
        <span class="dot-divider">•</span>
        于<%= @review.created_at_from_now %>发布
        <% if @review_comments.any? then %>
            <span class="dot-divider">•</span>
            最后由 <%= @review_comments.last.user.name %> 于<%= @review_comments.last.created_at_from_now %>回复
          <% end %>
        <span class="dot-divider">•</span>
        <%= @review.pageview %>次阅读
      </span>
    </div>
    <%= link_to add_cdn_path(image_tag 'portrait.gif', class: 'thumbnail pull-right portrait', style: 'margin-top: -6px;'), user_path(@review.user) %>
  </div>

  <div class="padding10">
    <!--<p id="notice"><%#= notice %></p>-->
    <p>
      <% if @review.details_available?(current_user?(@review.user)) then  %>
      <h5 style="display:<%= @review.company? ? 'none' : 'block' %>;">
        @<%= @review.company %>
      </h5>
      <%= @review.details.html_safe %>
    <% else %>
      <span class="text-warning">提示：无法查看该文章的具体内容，该文章被设置为私有。</span>
    <% end %>
    </p>
  </div>

  <div class="bottom-title-container">
    <% if signed_in? && current_user?(@review.user) then %>
      <%= link_to add_cdn_path(image_tag 'edit_24.png') + t('common.edit_btn_label'), edit_review_path(@review) %>
      <span class="divider">/</span>
      <%= link_to add_cdn_path(image_tag 'delete_24.png') + t('common.delete_btn_label'), @review, method: :delete, data: {confirm: (t 'common.alert.delete')} %>
      <span class="divider">/</span>
    <% end %>
    <%= link_to add_cdn_path(image_tag 'back_24.png') + '返回', reviews_path %>
  </div>
</div>

<% if @review.review_comments.any? then %>
  <div class="table-bordered border-left">
    <div class="top-title-container text-article-info">
      共收到<%= @review_comments.count %>条回复
      <%= will_paginate @review_comments %>
    </div>

    <% @review_comments.each do |review_comment| %>
      <table class="border-bottom" style="width: 100%;">
        <tr>
          <td class="padding10" style="width: 58px; vertical-align: top; border: 0;">
            <%= link_to add_cdn_path(image_tag 'portrait.gif', class: 'thumbnail portrait'), user_path(review_comment.user) %>
          </td>
          <td style="padding: 10px 10px 10px 0; border: 0;">
            <span class="text-article-info">
              <%= review_comment.user.name %>
              <span class="dot-divider">•</span>
              <%= review_comment.created_at_from_now %>
            </span>
            <br />
            <%= review_comment.details.html_safe %>
          </td>
        </tr>
      </table>
    <% end %>

    <div class="bottom-title-container text-article-info">
      共收到<%= @review_comments.count %>条回复
      <%= will_paginate @review_comments %>
    </div>
  </div>
<% end %>

<% if signed_in? then %>
  <div class="table-bordered border-left padding10 margin-top20">
    <%= render 'shared/comment_form', object: @review, comment: @review_comment %>
  </div>
<% end %>