config/routes.rb
Itshare::Application.routes.draw do
  resources :users do
    resources :messages, only: [:index, :new, :create, :destroy]
  end

  resources :jobs do
    resources :job_comments, only: [:create]
  end

  resources :reviews do
    resources :review_comments, only: [:create]
  end

  resources :experiences do
    resources :comments, only: [:create]
  end

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  get 'index', to: 'index#index'
  get 'about', to:'about#index'

  get 'auth/github', to: 'openid#github_auth', as: :auth_github

  get 'auth/github/callback', to: 'openid#github_auth_succeed'

  root to: 'index#index'

end

app/views/layouts/_footer.html.erb
<hr>

<footer>
  <p class="text-center">© guoyao 2013</p>
</footer>

<%#= debug(params) if Rails.env.development? %>

app/views/layouts/_head_template.html.erb
<meta charset="utf-8"/>
<!-- for sina weibo authentication
<meta property="wb:webmaster" content="e68c32bee4b74afb"/>-->
<%= add_cdn_path((favicon_link_tag 'favicon.ico'), 'href') %>
<title>IT资讯分享、求职、笔试、面试经验分享，IT企业工资待遇、企业文化点评...</title>
<meta name="Keywords" content="IT,资讯,分享,招聘,求职,笔试,面试,经验,IT企业,工资待遇,企业文化,点评"/>
<meta name="Description" content="IT分享网 专为IT职业人员分享求职、笔试、面试经验；爆料IT企业工资待遇、企业文化；提供一个空间给那些对现公司诸多不满的在职人员，空闲时来发发牢骚；为那些即将走出校园，走向社会的莘莘学子，以及那些蠢蠢欲动的在职人员提供宝贵的经验及内幕；"/>
<%= add_cdn_path((stylesheet_link_tag 'bootstrap', :media => 'all'), 'href') %>
<%= add_cdn_path((stylesheet_link_tag 'bootstrap-responsive', :media => 'all'), 'href') %>
<%= add_cdn_path((stylesheet_link_tag 'application', :media => 'all'), 'href') %>
<% if action_name == 'create' || action_name == 'update' || flash[:error] then %>
  <%= add_cdn_path((stylesheet_link_tag 'scaffolds', :media => 'all'), 'href') %>
<% end %>
<%= add_cdn_path(javascript_include_tag 'application') %>
<%= csrf_meta_tags %>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" style="padding-top: 6px; padding-bottom: 2px;" href="/">
        <%= add_cdn_path(image_tag 'share_32.png', style:"margin-top: -2px;") %>
        <%= t 'website.title' %>
      </a>

      <div class="nav-collapse collapse">
        <form class="navbar-form pull-right">
          <% if signed_in? then %>
            <div class="btn-group">
              <%= link_to current_user.name, user_path(current_user), class: 'btn btn-info' %>
              <a class="btn btn-info dropdown-toggle" data-toggle="dropdown" href="#">
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu pull-right">
                <li><%= link_to add_cdn_path(image_tag 'message_16.png') + t('controller.messages'), user_messages_path(current_user) %></li>
                <li><a href="#"><%= add_cdn_path(image_tag 'article_16.png') %>我的文章（暂未完成）</a></li>
                <li><a href="#"><%= add_cdn_path(image_tag 'people_16.png') %>我关注的人（暂未完成）</a></li>
                <li><a href="#"><%= add_cdn_path(image_tag 'favorite_16.png') %>我的收藏夹（暂未完成）</a></li>
                <li class="divider"></li>
                <li><a href="#"><%= add_cdn_path(image_tag 'user_info_16.png') %>个人资料修改（暂未完成）</a></li>
              </ul>
            </div>
            <%= link_to '退出', signout_path, method: "delete", :class => 'btn btn-danger' %>
          <% else %>
            <%= link_to '注册', signup_path, :class => 'btn btn-primary' %>
            <%= link_to '登录', signin_path, :class => 'btn btn-primary' %>
          <% end %>
        </form>
        <ul class="nav pull-right" style="margin-right: 6px;">
          <li class="<%= controller_name == 'index' ? 'active' : '' %>"><a href="/"><%= t 'controller.index' %></a></li>
          <li class="<%= controller_name == 'experiences' ? 'active' : '' %>"><%= link_to (t 'controller.experiences'), experiences_path %></li>
          <li class="<%= controller_name == 'reviews' ? 'active' : '' %>"><%= link_to (t 'controller.reviews'), reviews_path %></li>
          <li class="<%= controller_name == 'jobs' ? 'active' : '' %>"><%= link_to (t 'controller.jobs'), jobs_path %></li>
          <li class="<%= controller_name == 'about' ? 'active' : '' %>"><a href="/about"><%= t 'controller.about'%></a>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<% if signed_in? && new_record_path(true) then %>
  <div class="table-bordered border-left right-nav-container" style="color: #666666;">
    <div class="top-title-container" style="background-color: #eeeeee;">
      <b><%= t "controller.#{controller_name}" %></b>
    </div>
    <div class="padding10 text-center">
      <%= link_to (t 'controller.actions.new'), new_record_path(true), class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

<div class="table-bordered border-left right-nav-container" style="color: #666666;">
  <div class="top-title-container" style="background-color: #eeeeee;">
    <strong><%= t 'controller.experiences' %> - 文章排行</strong>
  </div>
  <ul class="article-list ranking-list">
    <% @ranking_experiences.each do |experience| %>
      <li>
        <%= link_to truncate(experience.title, length: 15), experience_path(experience) %>
        <span class="pull-right padding-right10 text-article-info"><%= experience.pageview %></span>
      </li>
    <% end %>
  </ul>
</div>

<div class="table-bordered border-left right-nav-container" style="color: #666666;">
  <div class="top-title-container" style="background-color: #eeeeee;">
    <strong><%= t 'controller.reviews' %> - 文章排行</strong>
  </div>
  <ul class="article-list ranking-list">
    <% @ranking_reviews.each do |review| %>
      <li>
        <%= link_to truncate(review.title, length: 15), review_path(review) %>
        <span class="pull-right padding-right10 text-article-info"><%= review.pageview %></span>
      </li>
    <% end %>
  </ul>
</div>

<div class="table-bordered border-left right-nav-container" style="color: #666666;">
  <div class="top-title-container" style="background-color: #eeeeee;">
    <strong><%= t 'controller.jobs' %> - 文章排行</strong>
  </div>
  <ul class="article-list ranking-list">
    <% @ranking_jobs.each do |job| %>
      <li>
        <%= link_to truncate(job.title, length: 15), job_path(job) %>
        <span class="pull-right padding-right10 text-article-info"><%= job.pageview %></span>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/_user_space_sidebar.html.erb
<div class="table-bordered border-left right-nav-container" style="color: #666666;">
  <div class="top-title-container">
    <strong>基本信息</strong>
  </div>
  <div class="padding10">
    <%= link_to (add_cdn_path(image_tag 'portrait.gif', class: 'thumbnail portrait pull-left', title: @user.name)), user_path(@user) %>
    <div style="margin-left: 67px;line-height: 28px;">
      <%= link_to @user.name, user_path(@user), title: gender_text(@user.gender) %><br />
      <%= add_cdn_path(gender_image_tag(@user.gender)) %> <%= link_to '关注此人', '#' %><br />
    </div>
    <div style="padding-top: 4px; line-height: 28px;">
      <span style="margin-right: 5px;"><%= link_to "#{t('common.fellow')}(0)", '#' %></span>
      <span style="margin-right: 5px;"><%= link_to "#{t('common.fans')}(0)", '#' %></span>
      <span><%= link_to "#{t('common.credits')}(0)", '#' %></span>
      <br/>
      加入时间：<%= "#{@user.created_at_string(t 'format.date.long')}（#{@user.created_at_wday_string}）" %>
    </div>
  </div>

  <% if signed_in? && current_user?(@user) %>
    <div class="top-title-container middle">
      <strong>个人信息管理</strong>
    </div>
    <div class="padding10">
      <%= link_to '站内留言', user_messages_path(@user) %>
    </div>
  <% end %>

  <div class="top-title-container middle">
    <strong>关注</strong>
  </div>
  <div class="padding10">

  </div>

  <div class="top-title-container middle">
    <strong>粉丝</strong>
  </div>
  <div class="padding10">

  </div>

  <div class="top-title-container middle">
    <strong>访客统计</strong>
  </div>
  <div class="padding10">

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head_template' %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <div class="row">
        <div class="span9">
          <%= yield %>
          <% if !signed_in? && (controller_name != 'sessions' && controller_name != 'index' &&
                  (controller_name != 'users' || (action_name != 'new' && action_name != 'create'))) then %>
            <div class="table-bordered border-left padding10 alert-error margin-top20">
              需要 <%= link_to '登录', signin_path, class: 'btn btn-primary' %>
              后方可发表和回复, 如果你还没有账号你可以 <%= link_to '注册', signup_path, :class => 'btn btn-primary' %> 一个帐号。
            </div>
          <% elsif new_record_path %>
            <div class="table-bordered border-left padding10 alert-error margin-top20">
              <%= link_to (t 'controller.actions.new'), new_record_path, class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
        <div class="span3 pull-right" style="margin-left: 0;">
          <%= render 'layouts/sidebar' %>
        </div>
      </div>

      <%= render 'layouts/footer' %>
    </div>

    <%= add_cdn_path(javascript_include_tag 'bootstrap') %>
  </body>
</html>

app/views/layouts/user_space.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head_template' %>
    <%#= add_cdn_path((stylesheet_link_tag 'users', :media => 'all'), 'href') %>
    <%= add_cdn_path((stylesheet_link_tag 'jquery.fancybox', :media => 'all'), 'href') %>
    <%= add_cdn_path(javascript_include_tag 'jquery.fancybox') %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <div class="row">
        <div class="span3">
          <%= render 'layouts/user_space_sidebar' %>
        </div>
        <div class="span9">
          <%= yield %>
        </div>
      </div>

      <%= render 'layouts/footer' %>
    </div>

    <%= add_cdn_path(javascript_include_tag 'bootstrap') %>
  </body>
</html>